language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
script: 
  - python -m arghandler.test
  - python -m arghandler.tests.decorator
  - python -m arghandler.tests.decorator2
notifications:
  email:
    recipients:
      - druths@networkdynamics.org
	on_success: never
	on_failure: always
